name: Publish (pypi prod)
# IMPORTANT NOTE: (see pypi guide)
# For security reasons, you must require manual approval on each run for the
# pypi environment.

on:
  release:
    types: [created]

env:
  PACKAGE_NAME: templatey
  PYTHON_VERSION_FOR_BUILD: 3.13
  UV_VERSION: "0.9.11"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 7

    steps:
      # Root path under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_FOR_BUILD }}

      - name: Set up UV (ubuntu one-shot)
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/${{env.UV_VERSION}}/install.sh | sh

      - name: Build
        run: uv build
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    # Only publish if current commit is tagged
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{env.PACKAGE_NAME}}
    permissions:
      id-token: write # Mandatory for trusted publishing

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish to PyPI (test)
      uses: pypa/gh-action-pypi-publish@release/v1

  # TODO: add sigstore step
  # See here for reference:
  #     https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
